python3 -m src.bench_vllm_multimodal \
    --model_name "Qwen/Qwen2-VL-7B-Instruct" \
    --dataset_name "alecocc/mathematic_games_dataset_en" \
    --out_dir "./out" \
    --max_samples 32 \
    --batch_size 4 \
    --cache_dir None \
    --n_out_sequences 8 \
    --temperature 0.8 \
    --top_p 1.0 \
    --mode cot \
    --text_only False \
    --n_gpus 1 